// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfIxAS2W5pduNUbZvixkm18JW7ZOymPVY',
    appId: '1:791240127140:web:8c7025ed45577234f3ac31',
    messagingSenderId: '791240127140',
    projectId: 'industry-move',
    authDomain: 'industry-move.firebaseapp.com',
    databaseURL: 'https://industry-move-default-rtdb.firebaseio.com',
    storageBucket: 'industry-move.appspot.com',
    measurementId: 'G-6ML2XX2XXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGkgK-MIt377-W5rFgOIoCab4Jy1Mtp9c',
    appId: '1:791240127140:android:95342de1d2bfb994f3ac31',
    messagingSenderId: '791240127140',
    projectId: 'industry-move',
    databaseURL: 'https://industry-move-default-rtdb.firebaseio.com',
    storageBucket: 'industry-move.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzfgBl7DOVNuDdYhGlHENSPAyjuo8A12c',
    appId: '1:791240127140:ios:5f8970a573d48898f3ac31',
    messagingSenderId: '791240127140',
    projectId: 'industry-move',
    databaseURL: 'https://industry-move-default-rtdb.firebaseio.com',
    storageBucket: 'industry-move.appspot.com',
    iosBundleId: 'com.example.company',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzfgBl7DOVNuDdYhGlHENSPAyjuo8A12c',
    appId: '1:791240127140:ios:d2e794c871716f47f3ac31',
    messagingSenderId: '791240127140',
    projectId: 'industry-move',
    databaseURL: 'https://industry-move-default-rtdb.firebaseio.com',
    storageBucket: 'industry-move.appspot.com',
    iosBundleId: 'com.example.company.RunnerTests',
  );
}
